// GENERATED by packaging/build_manifest.py -- do not edit.
window.FNS_MANIFEST = {
 "schema": 1,
 "release": "v3.0.0",
 "notes": "",
 "channel": "stable",
 "base_url": "https://storage.functionstr.com/fnstools",
 "toolkit": {
  "name": "FNSTools",
  "td_build": "099",
  "project": "FunctionStore_tools_2025_DEV.48.toe"
 },
 "core": [
  "FNS_ConfigRegistry",
  "FNS_MainMenuRegistry",
  "FNS_NavbarRegistry",
  "FNS_OpMenuRegistry",
  "FNS_PaneTypeRegistry",
  "FNS_ToolbarRegistry",
  "FNS_Updater"
 ],
 "categories": [
  "Core",
  "Surfaces",
  "Parameters",
  "Network",
  "Media & Output",
  "Control",
  "Workflow",
  "Developer"
 ],
 "packages": [
  {
   "name": "AltSelect",
   "kind": "tool",
   "category": "Network",
   "description": "Alternative selection helpers for operators in the network editor.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/altselect/",
   "surfaces": [],
   "shortcut": "ALT_SELECT",
   "ops": 97,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/AltSelect.tox",
    "bytes": 68470,
    "sha256": "bd4259afd8af33e6cac2949af9a72b42dea112c55039db56c3964bda19bc1889",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/AltSelect.tox"
   }
  },
  {
   "name": "AutoCombine",
   "kind": "tool",
   "category": "Network",
   "description": "Hold Alt while placing a generator TOP to have it come in pre-set to composite over its input.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/autocombine/",
   "surfaces": [],
   "shortcut": "AUTO_COMBINE",
   "ops": 124,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/AutoCombine.tox",
    "bytes": 81318,
    "sha256": "21becf12d5a02c53d1bb8029a493e37968b3c53cb87c517bfd80e1ebf5c3ce6e",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/AutoCombine.tox"
   }
  },
  {
   "name": "AutoRes",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Project-wide resolution reference that operators can follow instead of hardcoding pixel sizes.",
   "version": "1.0.4",
   "help_url": "https://tools.functionstore.xyz/docs/autores/",
   "surfaces": [],
   "shortcut": "AUTO_RES",
   "ops": 124,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/AutoRes.tox",
    "bytes": 81070,
    "sha256": "ef6fd2490a4390db5aaee27684c5a853ed209127ff6e919401292ddbe029e656",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/AutoRes.tox"
   }
  },
  {
   "name": "BorderlessTD",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Borderless TouchDesigner window, plus timeline hiding.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/borderlesstd/",
   "surfaces": [
    "mainmenu"
   ],
   "shortcut": "FNS_BORDERLESS_TD",
   "ops": 369,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_MainMenuRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/BorderlessTD.tox",
    "bytes": 228438,
    "sha256": "9c74cb9c90d3d116de18a7381ec933001dcdc78447b94225a7d0ed5789ef3257",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/BorderlessTD.tox"
   }
  },
  {
   "name": "ColorUI",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Operator and family colour palettes, with the active palette roaming through config.",
   "version": "1.0.2",
   "help_url": "https://tools.functionstore.xyz/docs/colorui/",
   "surfaces": [
    "tools_ui"
   ],
   "shortcut": "FNS_COLOR_UI",
   "ops": 165,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/ColorUI.tox",
    "bytes": 102646,
    "sha256": "c26369048241026fe92412da9f2224a535f7f98d7597eab8065dfeb922ba7774",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/ColorUI.tox"
   }
  },
  {
   "name": "CustomParTools",
   "kind": "tool",
   "category": "Parameters",
   "description": "Promote parameters to a parent with binds or expressions, customize name/label/range on drop, plus extension creation, parent shortcuts, parameter clearing and IOP promotion.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/custompartools/",
   "surfaces": [
    "navbar",
    "toolbar"
   ],
   "shortcut": "FNS_CPP",
   "ops": 938,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_NavbarRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [
    "QuickCollapse"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/CustomParTools.tox",
    "bytes": 548680,
    "sha256": "36413aa1d3710128430f48ce30c8347226b40cec599180c659271c94244e4819",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/CustomParTools.tox"
   }
  },
  {
   "name": "ExprHotStrings",
   "kind": "tool",
   "category": "Parameters",
   "description": "Abbreviations that expand into TouchDesigner expressions as you type in a parameter field.",
   "version": "1.1.1",
   "help_url": "https://tools.functionstore.xyz/docs/exprhotstrings/",
   "surfaces": [
    "tools_ui"
   ],
   "shortcut": "HOTSTRINGS",
   "ops": 114,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [
    "CustomParTools"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "portability": [
    {
     "op": "ExprHotStrings_tab",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/ExprHotStrings_tab.tsv"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/ExprHotStrings.tox",
    "bytes": 77510,
    "sha256": "60c0cdc3f695bf7a53b8545be616e71a181a60c209ecad130f51b1555950d8b9",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/ExprHotStrings.tox"
   }
  },
  {
   "name": "FNS_ConfigRegistry",
   "kind": "core",
   "category": "Core",
   "description": "Settings persistence registry: one aggregated JSON in the user palette, so preferences follow you across projects and survive updates. The raw master, promoted to /sys.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/fns-configregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 36,
   "requires": [],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_ConfigRegistry.tox",
    "bytes": 47766,
    "sha256": "31fc7f5656bac02c8be7f62cf746054e480151af2e5b10ce0736e8c2d5b03cc2",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_ConfigRegistry.tox"
   }
  },
  {
   "name": "FNS_HotkeyManager",
   "kind": "tool",
   "category": "Workflow",
   "description": "Unified hotkey discovery, conflict detection and rebinding UI across the whole toolkit.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/fns-hotkeymanager/",
   "surfaces": [],
   "shortcut": "FNS_HOTKEY_MANAGER",
   "ops": 198,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "portability": [
    {
     "op": "table_gathered_hotkeys",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/Hotkeys.tsv"
    },
    {
     "op": "table_gathered_hotkeys1",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/Hotkeys.tsv"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_HotkeyManager.tox",
    "bytes": 143926,
    "sha256": "b85f2b52a53ab416b6953fee2da785cb86fea3383fe66162d1760f9ee71286e4",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_HotkeyManager.tox"
   }
  },
  {
   "name": "FNS_MainMenu",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Main-menu extras: the menu Configurator UI.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/fns-mainmenu/",
   "surfaces": [
    "mainmenu"
   ],
   "shortcut": "FNS_MAINMENU",
   "ops": 337,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_MainMenuRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "root",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_MainMenu.tox",
    "bytes": 223438,
    "sha256": "d05818f90c579caff293ff35eeb25075403e528c6e08ea7a06bfbbadc289e988",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_MainMenu.tox"
   }
  },
  {
   "name": "FNS_MainMenuRegistry",
   "kind": "core",
   "category": "Core",
   "description": "TD main-menu surface registry, including project-name display. The raw master, promoted to /sys.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/fns-mainmenuregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 33,
   "requires": [],
   "integrates_with": [
    "FNS_MainMenu"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_MainMenuRegistry.tox",
    "bytes": 42734,
    "sha256": "6cba821d6fdd7426d1acbcdeaa3d5e442bbb378262c15def33c7760fbe712ae7",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_MainMenuRegistry.tox"
   }
  },
  {
   "name": "FNS_Navbar",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Pane-bar extras: parent-hierarchy navigation, path injection and drag-drop hijack, plus the navbar Configurator.",
   "version": "1.0.3",
   "help_url": "https://tools.functionstore.xyz/docs/fns-navbar/",
   "surfaces": [
    "navbar"
   ],
   "shortcut": "FNS_NAVBAR",
   "ops": 1516,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_NavbarRegistry"
   ],
   "integrates_with": [
    "CustomParTools"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "the drag-drop hijack guards against panenav not existing yet on first load into a bare project, retrying briefly instead of erroring the install.",
   "artifact": {
    "path": "packaging/dist/FNS_Navbar.tox",
    "bytes": 594352,
    "sha256": "8964eb3df37be52f1f188a3670953f06223017b74b85f0e6d341a7dc9663c837",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_Navbar.tox"
   }
  },
  {
   "name": "FNS_NavbarRegistry",
   "kind": "core",
   "category": "Core",
   "description": "The pane-bar surface registry. The raw master, promoted to /sys -- clone it to add your own pane-bar widgets.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/fns-navbarregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 33,
   "requires": [],
   "integrates_with": [
    "FNS_Navbar",
    "FNS_Toolbar"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_NavbarRegistry.tox",
    "bytes": 42830,
    "sha256": "09949f6a0950859be312831da79d4b7f0f341140f3dfc167fed0e020d1145e29",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_NavbarRegistry.tox"
   }
  },
  {
   "name": "FNS_OpMenu",
   "kind": "tool",
   "category": "Surfaces",
   "description": "OP Create dialog extras: the IO filter, operator search words and script injection.",
   "version": "1.0.3",
   "help_url": "https://tools.functionstore.xyz/docs/fns-opmenu/",
   "surfaces": [
    "opmenu",
    "tools_ui"
   ],
   "shortcut": "FNS_OPMOD",
   "ops": 291,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_OpMenuRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "portability": [
    {
     "op": "OpSearchWords",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/OpSearchWords.tsv"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_OpMenu.tox",
    "bytes": 181582,
    "sha256": "ec7b2defe687441c10652b1e363ccb4c0c7d377761fca93744f7bdeb63664ef6",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_OpMenu.tox"
   }
  },
  {
   "name": "FNS_OpMenuRegistry",
   "kind": "core",
   "category": "Core",
   "description": "OP Create dialog surface registry: search words, row decorations, right-click items, filter stages. The raw master, promoted to /sys.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/fns-opmenuregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 34,
   "requires": [],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_OpMenuRegistry.tox",
    "bytes": 45014,
    "sha256": "326ee13a07868768f935ae65ac6601384250e0ee03435b84f8f48d442a006121",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_OpMenuRegistry.tox"
   }
  },
  {
   "name": "FNS_PaneTypeRegistry",
   "kind": "core",
   "category": "Core",
   "description": "Named, persistent pane-type entries for TD's panebar: any COMP can appear in the pane-type dropdown and be recalled with configurable owner, type, window actions and callbacks.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/fns-panetyperegistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 227,
   "requires": [],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "portability": [
    {
     "op": "md",
     "par": "externaltox",
     "kind": "project",
     "path": "<repo>/modules/suspects/FNSTools/../../../../../VJ/TD/Downloaded/dotsimulate/md_0.0.3.tox"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_PaneTypeRegistry.tox",
    "bytes": 150574,
    "sha256": "c2d0a1a513bf684516a68479ad218bb5dc5607d3b245015bfd709e369fe63b78",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_PaneTypeRegistry.tox"
   }
  },
  {
   "name": "FNS_Toolbar",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Toolbar extras: the Configurator UI for ordering, grouping and hiding bar widgets, plus stock widgets.",
   "version": "1.0.5",
   "help_url": "https://tools.functionstore.xyz/docs/fns-toolbar/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_TOOLBAR",
   "ops": 564,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [
    "BorderlessTD"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_Toolbar.tox",
    "bytes": 332566,
    "sha256": "f935673254cdc631cc2a8dfffa174df3d3b3db016dedf3683c4f8877dba863f5",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_Toolbar.tox"
   }
  },
  {
   "name": "FNS_ToolbarRegistry",
   "kind": "core",
   "category": "Core",
   "description": "The toolbar surface registry and mirror rail. The raw master, promoted to /sys -- clone it to put your own tools on the bar.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/fns-toolbarregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 32,
   "requires": [],
   "integrates_with": [
    "FNS_Toolbar"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_ToolbarRegistry.tox",
    "bytes": 38318,
    "sha256": "6c8994fc2f5c0a27707cae6d0381ccdf0b367f7e3b104d9878a6259f1d68e7be",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_ToolbarRegistry.tox"
   }
  },
  {
   "name": "FNS_Updater",
   "kind": "core",
   "category": "Developer",
   "description": "In-place toolkit updates, with settings preserved across the replacement.",
   "version": "1.0.9",
   "help_url": "https://tools.functionstore.xyz/docs/fns-updater/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_UPDATER",
   "ops": 183,
   "requires": [],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_Updater.tox",
    "bytes": 138358,
    "sha256": "87ba8bd46b6adc50af96ea30cb1907399c0883604e4152d1d532d25ff12bd4cc",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/FNS_Updater.tox"
   }
  },
  {
   "name": "GlobalOutSelect",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Browse Global OP Shortcuts and the out operators inside them in a tree, and drag any of them into a network as a Select.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/globaloutselect/",
   "surfaces": [
    "tools_ui"
   ],
   "shortcut": "GLOBAL_OUT_SEL",
   "ops": 750,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/GlobalOutSelect.tox",
    "bytes": 184014,
    "sha256": "81f544a908ab037310ae2cebdcab0d6fa90cc178d56bd4495f0973b88332b057",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/GlobalOutSelect.tox"
   }
  },
  {
   "name": "GlobalVolControl",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Global audio volume control.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/globalvolcontrol/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_VolControl",
   "ops": 229,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/GlobalVolControl.tox",
    "bytes": 165278,
    "sha256": "0f9712e305f42c7d344d8e66c191f7c41f38ff4ae13d4e4c61cc1fdf05556a29",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/GlobalVolControl.tox"
   }
  },
  {
   "name": "HydroHomie",
   "kind": "tool",
   "category": "Media & Output",
   "description": "A toolbar reminder to drink water at an interval you set. Off by default.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/hydrohomie/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_HYDROHOMIE",
   "ops": 203,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/HydroHomie.tox",
    "bytes": 122934,
    "sha256": "9900e4b659bc0b81ce6cd8ab976f814a17efb9b6869840e72de8b0c6046dd74b",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/HydroHomie.tox"
   }
  },
  {
   "name": "midiMapper",
   "kind": "tool",
   "category": "Control",
   "description": "Map MIDI controls to parameters, with a learn mode you drive by dropping a parameter on the toolbar button. Mappings are saved into the project folder by design; the tool's own settings roam through config.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/midimapper/",
   "surfaces": [
    "toolbar",
    "tools_ui"
   ],
   "shortcut": "FNS_MULTIMIDI",
   "ops": 389,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "root",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/midiMapper.tox",
    "bytes": 202958,
    "sha256": "80f662deff49db7a3684136427f260b5ab23404fb57086aa660a04aa9ce551a9",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/midiMapper.tox"
   }
  },
  {
   "name": "MISC",
   "kind": "tool",
   "category": "Workflow",
   "description": "Assorted small utilities that ship together (hog CHOP, mouse input and friends).",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/misc/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_MISC",
   "ops": 153,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/MISC.tox",
    "bytes": 126806,
    "sha256": "bb0b2fe5c20f60fec186220cab5955466d9132e5597886c2c8f2231ae38ff489",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/MISC.tox"
   }
  },
  {
   "name": "MY_HOTKEYS",
   "kind": "tool",
   "category": "Workflow",
   "description": "Convenience hotkeys over stock TouchDesigner actions: open parameters, open the COMP editor, focus the palette search.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/my-hotkeys/",
   "surfaces": [],
   "shortcut": "FNS_HOTKEYS",
   "ops": 95,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/MY_HOTKEYS.tox",
    "bytes": 67150,
    "sha256": "04e22b160a3dd267daaba56b275d40704459264bf8d924a982957ef516ba9944",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/MY_HOTKEYS.tox"
   }
  },
  {
   "name": "OpenExt",
   "kind": "tool",
   "category": "Developer",
   "description": "Open an operator's extension source quickly.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/openext/",
   "surfaces": [],
   "shortcut": "",
   "ops": 89,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/OpenExt.tox",
    "bytes": 67534,
    "sha256": "499c9265efe0f3281dfbf8f48ea13b9bb45e24842d0816f75400d8eba34abd07",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/OpenExt.tox"
   }
  },
  {
   "name": "OpTemplates",
   "kind": "tool",
   "category": "Network",
   "description": "A library of preconfigured operator templates to drop into a network.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/optemplates/",
   "surfaces": [
    "opmenu",
    "toolbar"
   ],
   "shortcut": "FNS_OPTEMPLATES",
   "ops": 588,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_OpMenuRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [
    "AutoRes"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "portability": [
    {
     "op": "OPTemplates1",
     "par": "externaltox",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/OpTemplates/OPTemplates1.tox"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP/cam1/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Contents/Resources/tfs/Samples/Geo/defcam.geo"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP/null1/cross1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Contents/Resources/tfs/Samples/Geo/defnull.geo"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP/light1/cross1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Contents/Resources/tfs/Samples/Geo/defnull.geo"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP_ortho/cam1/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Contents/Resources/tfs/Samples/Geo/defcam.geo"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP_ortho/null1/cross1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Contents/Resources/tfs/Samples/Geo/defnull.geo"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP_ortho/light1/cross1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Contents/Resources/tfs/Samples/Geo/defnull.geo"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/OpTemplates.tox",
    "bytes": 275288,
    "sha256": "962d9f6956cd11cbf4d421c189ebccfd1695d552c3b509865a98d8126e55e55e",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/OpTemplates.tox"
   }
  },
  {
   "name": "OpToClipboard",
   "kind": "tool",
   "category": "Network",
   "description": "Copy the selected operator's reference to the system clipboard, ready to paste into an expression.",
   "version": "1.0.4",
   "help_url": "https://tools.functionstore.xyz/docs/optoclipboard/",
   "surfaces": [],
   "shortcut": "",
   "ops": 102,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/OpToClipboard.tox",
    "bytes": 69158,
    "sha256": "a5998371ae9d22c556e64d68d8c2528952e9d0fac620604ddb701f1620dfccb2",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/OpToClipboard.tox"
   }
  },
  {
   "name": "oscMapper",
   "kind": "tool",
   "category": "Control",
   "description": "Map OSC messages to parameters. Mappings are saved into the project folder by design.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/oscmapper/",
   "surfaces": [
    "tools_ui"
   ],
   "shortcut": "AMB_OSC_MAPPER",
   "ops": 257,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/oscMapper.tox",
    "bytes": 126750,
    "sha256": "f3ceed4b3590f991cbf26cb4ac9ce88bd3740382a245bfab7ee60eb85e33fbbb",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/oscMapper.tox"
   }
  },
  {
   "name": "OUTPUT",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Output window and display routing helpers.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/output/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_OUTPUT",
   "ops": 111,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/OUTPUT.tox",
    "bytes": 98414,
    "sha256": "31cb08c1ca6b1c625cbfba43fe3df0bc134c6311115877f770cb38b6e735658c",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/OUTPUT.tox"
   }
  },
  {
   "name": "ParOPDrop",
   "kind": "tool",
   "category": "Parameters",
   "description": "Create Parameter CHOP/DAT and Parameter Execute DAT nodes inside a COMP from its custom parameters, by drag and drop or hotkey.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/paropdrop/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_POP",
   "ops": 154,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/ParOPDrop.tox",
    "bytes": 110598,
    "sha256": "b98abd6dfbdfcc4cfd63e716be807c4ca47de35e505e191f7632ab43ceaeebe3",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/ParOPDrop.tox"
   }
  },
  {
   "name": "ParRandomizer",
   "kind": "tool",
   "category": "Parameters",
   "description": "Randomize parameter values within range, for quick exploration.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/parrandomizer/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_PARRANDOM",
   "ops": 152,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/ParRandomizer.tox",
    "bytes": 111774,
    "sha256": "26de2576e4c2d9e06d568b27373d7135b7d463c2ae60528349c3fc6bd05b6f61",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/ParRandomizer.tox"
   }
  },
  {
   "name": "paste_from_clipboard",
   "kind": "tool",
   "category": "Network",
   "description": "Paste images and data from the system clipboard into TouchDesigner.",
   "version": "1.0.5",
   "help_url": "https://tools.functionstore.xyz/docs/paste-from-clipboard/",
   "surfaces": [],
   "shortcut": "",
   "ops": 204,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "root",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/paste_from_clipboard.tox",
    "bytes": 131542,
    "sha256": "c66e71f06931e85b01e3cd7f46423da397c4300f77d2c93b0f07a8b17780f2a7",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/paste_from_clipboard.tox"
   }
  },
  {
   "name": "QuickCollapse",
   "kind": "tool",
   "category": "Network",
   "description": "Collapse a selection into a component, with an optional customize dialog.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/quickcollapse/",
   "surfaces": [],
   "shortcut": "FNS_QUICKCOLLAPSE",
   "ops": 189,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/QuickCollapse.tox",
    "bytes": 101038,
    "sha256": "b9ee99542c4ad00a009a86d58cd6a664696f4d8c05329df286919eb8f7327373",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/QuickCollapse.tox"
   }
  },
  {
   "name": "QuickMarks",
   "kind": "tool",
   "category": "Network",
   "description": "Bookmark network locations and jump back to them. Bookmarks stay project-local by design.",
   "version": "1.0.0",
   "help_url": "https://alex-guevara.com",
   "surfaces": [],
   "shortcut": "",
   "ops": 44,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "root",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/QuickMarks.tox",
    "bytes": 48054,
    "sha256": "2c226f5f33cc8455a31513ba803975d19593a2df9369e23b821008eecd6820db",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/QuickMarks.tox"
   }
  },
  {
   "name": "QuickPane",
   "kind": "tool",
   "category": "Workflow",
   "description": "Pane layout shortcuts.",
   "version": "1.0.5",
   "help_url": "https://tools.functionstore.xyz/docs/quickpane/",
   "surfaces": [],
   "shortcut": "",
   "ops": 120,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/QuickPane.tox",
    "bytes": 70478,
    "sha256": "0ed8cf98976baa13d9da2b0828f053f8287f80c8b7fa467af0b114f266d74108",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/QuickPane.tox"
   }
  },
  {
   "name": "QuickParCustom",
   "kind": "tool",
   "category": "Parameters",
   "description": "Fast custom-parameter editing on the focused operator.",
   "version": "1.0.0",
   "help_url": "https://github.com/function-store/FunctionStore_tools/wiki/03.-Miscellaneous#quickparcustom",
   "surfaces": [],
   "shortcut": "",
   "ops": 138,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [
    "CustomParTools"
   ],
   "tox_carrier": "root",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/QuickParCustom.tox",
    "bytes": 89846,
    "sha256": "1c2facc959d63061e3a4e32c620e544a9a519cf8d9130dffd1ecb1501f04583b",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/QuickParCustom.tox"
   }
  },
  {
   "name": "QuickTime",
   "kind": "tool",
   "category": "Workflow",
   "description": "Timeline and time-related shortcuts.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/quicktime/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_QUICKTIME",
   "ops": 148,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/QuickTime.tox",
    "bytes": 107966,
    "sha256": "1061567f171b3ce598c6365afff1c1bd76ffd382cba54544651ef03e8cd7c7a3",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/QuickTime.tox"
   }
  },
  {
   "name": "ResetPLS1",
   "kind": "tool",
   "category": "Workflow",
   "description": "Reset stateful operators (feedback, cache, timers, counts) across the project, with a pattern-based exception list. Bound to ctrl+0.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/resetpls1/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_RPLS",
   "ops": 218,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "portability": [
    {
     "op": "table_except_static",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/table_except_static.tsv"
    },
    {
     "op": "table_custom_resetpars",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/table_custom_resetpars.tsv"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/ResetPLS1.tox",
    "bytes": 126702,
    "sha256": "3a8fe81d57679b006d6904334c7d424737c18e2fa36e1871941ecaaf2b94be02",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/ResetPLS1.tox"
   }
  },
  {
   "name": "SetSmoothness",
   "kind": "tool",
   "category": "Control",
   "description": "Set Input/Viewer Smoothness on selected TOPs, or on every TOP in the network.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/setsmoothness/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "SMOOTHNESS_SET",
   "ops": 250,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/SetSmoothness.tox",
    "bytes": 166182,
    "sha256": "d70b8ec5056004c9ee325ade959cae63932ed281a94ae20ab4749cc01f5a2510",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/SetSmoothness.tox"
   }
  },
  {
   "name": "SwapOps",
   "kind": "tool",
   "category": "Network",
   "description": "Swap one operator for another while keeping connections intact.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/swapops/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "SWAP_OPS",
   "ops": 134,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/SwapOps.tox",
    "bytes": 109022,
    "sha256": "c391ca338cfadb5bb4c31b7ba47b4a518371e1a3a1382d3e8e9f826a3df52500",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/SwapOps.tox"
   }
  },
  {
   "name": "SwitchOPs",
   "kind": "tool",
   "category": "Network",
   "description": "Switch between operators in place.",
   "version": "1.0.1",
   "help_url": "https://tools.functionstore.xyz/docs/switchops/",
   "surfaces": [],
   "shortcut": "FNS_SWITCHOP",
   "ops": 95,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/SwitchOPs.tox",
    "bytes": 67982,
    "sha256": "a257dec81367124cc63ba183ba856bf092688e205de9abb738db4c3b95ecff17",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/SwitchOPs.tox"
   }
  },
  {
   "name": "TDX_SearchPalette",
   "kind": "tool",
   "category": "Workflow",
   "description": "Search field for TouchDesigner's palette browser, installed into the palette on startup. Vendored TD-SearchPalette by Yea Chen.",
   "version": "1.1.0",
   "help_url": "https://tools.functionstore.xyz/docs/tdx-searchpalette/",
   "surfaces": [],
   "shortcut": "TDX_SEARCH_PALETTE",
   "ops": 111,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/TDX_SearchPalette.tox",
    "bytes": 57286,
    "sha256": "dff1701e74fd1a9cdd6defa87bca4efc31aa8831bfd594135a6235b6886242c8",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/TDX_SearchPalette.tox"
   }
  },
  {
   "name": "tools_ui",
   "kind": "tool",
   "category": "Surfaces",
   "description": "The tabbed panel that hosts the toolkit's larger tool UIs.",
   "version": "1.1.0",
   "help_url": "https://tools.functionstore.xyz/docs/tools-ui/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "MY_UI",
   "ops": 284,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/tools_ui.tox",
    "bytes": 122062,
    "sha256": "dcefb8d5e494b221c2e0ae1c0211d371c5319d5e0a062511089346957c53fdc3",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/tools_ui.tox"
   }
  },
  {
   "name": "VSCodeTools",
   "kind": "tool",
   "category": "Developer",
   "description": "VS Code integration: open externalized scripts, sync files and generate TouchDesigner type stubs.",
   "version": "1.0.0",
   "help_url": "https://tools.functionstore.xyz/docs/vscodetools/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_VSCODETOOLS",
   "ops": 389,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/VSCodeTools.tox",
    "bytes": 630560,
    "sha256": "2c42f95cc52d90cabf3b28e2305bd53b5e70c14b7cba98a33bfc0b95e2379d46",
    "url": "https://storage.functionstr.com/fnstools/v3.0.0/VSCodeTools.tox"
   }
  }
 ]
};
