// GENERATED by packaging/build_manifest.py -- do not edit.
window.FNS_MANIFEST = {
 "schema": 1,
 "release": "v3.1.4",
 "notes": "Every tool: every package now runs the shared export strip. Twenty-five\npackages, every registry among them, had no hook for it and shipped their\nauthoring bookkeeping (Version Ctrl pages and tables) and the dev\nproject's paths in their FNS_About. The strip also writes the About\npage's Owner as an expression that resolves wherever the tool lands.",
 "channel": "stable",
 "base_url": "https://storage.functionstore.tools/fnstools",
 "toolkit": {
  "name": "FNSTools",
  "td_build": "2025.33070",
  "project": "FNSTools_PRIV.toe",
  "support_url": "https://patreon.com/function_store",
  "tiers": [
   {
    "id": "8323905",
    "label": "Base"
   },
   {
    "id": "8291595",
    "label": "Pro"
   },
   {
    "id": "9796651",
    "label": "Coaching"
   }
  ],
  "surface_meta": {
   "console": {
    "label": "Console tab",
    "registry": "FNS_Console"
   },
   "hub": {
    "label": "Hub tab",
    "registry": "FNS_HubRegistry"
   },
   "mainmenu": {
    "label": "Main menu entry",
    "registry": "FNS_MainMenuRegistry"
   },
   "navbar": {
    "label": "Pane bar button",
    "registry": "FNS_NavbarRegistry"
   },
   "opmenu": {
    "label": "OP Create menu entry",
    "registry": "FNS_OpMenuRegistry"
   },
   "panebar": {
    "label": "Custom pane type",
    "registry": "FNS_PaneTypeRegistry"
   },
   "timeline": {
    "label": "Timeline panel",
    "registry": "FNS_TimelineRegistry"
   },
   "toolbar": {
    "label": "Toolbar button",
    "registry": "FNS_ToolbarRegistry"
   }
  }
 },
 "core": [
  "FNS_ConfigRegistry",
  "FNS_Console",
  "FNS_Hub",
  "FNS_HubRegistry",
  "FNS_MainMenuRegistry",
  "FNS_NavbarRegistry",
  "FNS_OpMenuRegistry",
  "FNS_PaneTypeRegistry",
  "FNS_ToolbarRegistry",
  "FNS_Updater"
 ],
 "retired": [
  "FNS_Media"
 ],
 "minimum_updater": "",
 "notices": [
  "FNSTools v3.1.0 is a beta. If a download or install stalls, leave it as it is and send the Textport contents to Function Store on Discord or Patreon."
 ],
 "categories": [
  "Core",
  "Surfaces",
  "Parameters",
  "Network",
  "Media & Output",
  "Control",
  "Workflow",
  "Developer"
 ],
 "category_meta": {
  "Core": {
   "glyph": "\u25c8",
   "pitch": "The registries every other tool plugs into. Installed as a unit.",
   "deprioritized": true
  },
  "Surfaces": {
   "glyph": "\u25a6",
   "pitch": "The parts of TouchDesigner you look at all day, made yours."
  },
  "Parameters": {
   "glyph": "\u25ce",
   "pitch": "Promote, bind, randomize and reset, by drag and drop."
  },
  "Network": {
   "glyph": "\u21c4",
   "pitch": "Build, swap, collapse and navigate without touching a menu."
  },
  "Media & Output": {
   "glyph": "\u25b6",
   "pitch": "Where the picture and the sound actually leave the project."
  },
  "Control": {
   "glyph": "\u2299",
   "pitch": "Hardware in, parameters out."
  },
  "Workflow": {
   "glyph": "\u26a1",
   "pitch": "The small frictions, removed."
  },
  "Developer": {
   "glyph": "\u2328",
   "pitch": "Extensions, stubs and the editor you actually write them in."
  }
 },
 "starter": [
  "AutoRes",
  "CustomParTools",
  "FNS_HotkeyManager",
  "FNS_Navbar",
  "FNS_OpMenu",
  "FNS_TimelineTools",
  "FNS_Toolbar",
  "OpToClipboard",
  "ParOPDrop",
  "QuickCollapse",
  "QuickPane",
  "SwapOps",
  "TDX_SearchPalette"
 ],
 "packages": [
  {
   "name": "AltSelect",
   "title": "AltSelect",
   "kind": "tool",
   "category": "Network",
   "description": "Alternative selection helpers for operators in the network editor.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/altselect/",
   "surfaces": [],
   "shortcut": "ALT_SELECT",
   "ops": 72,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/AltSelect.tox",
    "bytes": 129110,
    "sha256": "ddcc273747aba5d9fb0f795a771b77f3f36d73a86ed0e386273ac1fa9a6c9468",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/AltSelect.tox"
   }
  },
  {
   "name": "AutoCombine",
   "title": "AutoCombine",
   "kind": "tool",
   "category": "Network",
   "description": "Hold Alt while placing a generator TOP to have it come in pre-set to composite over its input.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/autocombine/",
   "surfaces": [],
   "shortcut": "AUTO_COMBINE",
   "ops": 99,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/AutoCombine.tox",
    "bytes": 142390,
    "sha256": "18318a23c587e5586ec33955b054e0197bd12ac665c227fcb7dd2034b978036e",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/AutoCombine.tox"
   }
  },
  {
   "name": "AutoRes",
   "title": "AutoRes",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Project-wide resolution reference that operators can follow, with no hardcoded pixel sizes.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/autores/",
   "surfaces": [],
   "shortcut": "AUTO_RES",
   "ops": 99,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/AutoRes.tox",
    "bytes": 142094,
    "sha256": "8c65d60bfbe824426a0403c7cde6554d5491394b5f262d55fe1f083d1ec17600",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/AutoRes.tox"
   }
  },
  {
   "name": "BorderlessTD",
   "title": "BorderlessTD",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Borderless TouchDesigner window, plus timeline hiding.",
   "version": "3.0.5",
   "help_url": "https://functionstore.tools/docs/borderlesstd/",
   "surfaces": [
    "mainmenu",
    "toolbar"
   ],
   "shortcut": "FNS_BORDERLESS_TD",
   "ops": 268,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_MainMenuRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "F7",
     "op": "BorderlessTD",
     "par": "Shortcutmakeborderless"
    },
    {
     "keys": "alt.F7",
     "op": "BorderlessTD",
     "par": "Shortcut"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/BorderlessTD.tox",
    "bytes": 396726,
    "sha256": "9afbe22ef2d146c8e5e775961d4b9f21f2f9a6e4bdd4d225452d7c213ccd5068",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/BorderlessTD.tox"
   }
  },
  {
   "name": "ColorUI",
   "title": "ColorUI",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Operator and family colour palettes, with the active palette roaming through config.",
   "version": "3.0.6",
   "help_url": "https://functionstore.tools/docs/colorui/",
   "surfaces": [
    "console",
    "hub"
   ],
   "shortcut": "FNS_COLOR_UI",
   "ops": 145,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_Console",
    "FNS_HubRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/ColorUI.tox",
    "bytes": 288358,
    "sha256": "48ae1feee65fc8bef78386c55b4308cda162d813c3db1d471e7810df91e6ebc6",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/ColorUI.tox"
   }
  },
  {
   "name": "CustomParTools",
   "title": "CustomParTools",
   "kind": "tool",
   "category": "Parameters",
   "description": "Promote parameters to a parent with binds or expressions, customize name/label/range on drop, plus extension creation, parent shortcuts, parameter clearing and IOP promotion. Also carries four stock-TouchDesigner shortcuts for opening parameters and the COMP editor.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/custompartools/",
   "surfaces": [
    "navbar",
    "toolbar"
   ],
   "shortcut": "FNS_CPP",
   "ops": 898,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_NavbarRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [
    "QuickCollapse"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "alt.\\",
     "op": "QuickParCustom",
     "par": "Shortcutrollovercustomize"
    },
    {
     "keys": "alt.x",
     "op": "QuickParCustom",
     "par": "Shortcutrolloverpromote"
    },
    {
     "keys": "ctrl.alt.\\",
     "op": "QuickParCustom",
     "par": "Shortcutrolloverswitchparmode"
    },
    {
     "keys": "ctrl.alt.q",
     "op": "CustomParTools",
     "par": "Shortcutparentpars"
    },
    {
     "keys": "ctrl.alt.w",
     "op": "CustomParTools",
     "par": "Shortcutparentcomp"
    },
    {
     "keys": "shift.alt.q",
     "op": "CustomParTools",
     "par": "Shortcutcurrentpars"
    },
    {
     "keys": "shift.alt.w",
     "op": "CustomParTools",
     "par": "Shortcutcurrentcomp"
    },
    {
     "keys": "shift.alt.x",
     "op": "QuickParCustom",
     "par": "Shortcutrolloverpromotemod"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/CustomParTools.tox",
    "bytes": 1072538,
    "sha256": "2e6109e51a3b07384a75529fa4e67aceff3d8e860d4f6ceeccdd75ef6cb96ab9",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/CustomParTools.tox"
   }
  },
  {
   "name": "ExprHotStrings",
   "title": "ExprHotStrings",
   "kind": "tool",
   "category": "Parameters",
   "description": "Abbreviations that expand into TouchDesigner expressions as you type in a parameter field.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/exprhotstrings/",
   "surfaces": [
    "hub"
   ],
   "shortcut": "HOTSTRINGS",
   "ops": 104,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_HubRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [
    "CustomParTools"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "portability": [
    {
     "op": "ExprHotStrings_tab",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/ExprHotStrings_tab.tsv"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/ExprHotStrings.tox",
    "bytes": 191270,
    "sha256": "b4b59856203c3244ab28b16564b4e62e82f91255a9b520908a670f74b63b9026",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/ExprHotStrings.tox"
   }
  },
  {
   "name": "FNS_Autosave",
   "title": "Autosave",
   "kind": "tool",
   "category": "Workflow",
   "description": "Save the project on a timer without touching the timeline, honouring your increment and backup preferences, and skipping saves while you are performing.",
   "version": "1.0.3",
   "help_url": "https://functionstore.tools/docs/fns-autosave/",
   "surfaces": [],
   "shortcut": "",
   "ops": 47,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "launcher": {
    "surfaces": [
     "context-menu",
     "session"
    ],
    "capabilities": [
     "fns.autosave"
    ],
    "seedable": true
   },
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_Autosave.tox",
    "bytes": 116086,
    "sha256": "e1bddc0073f5bc3c2158fad366992e2fea0470f4f65e95cd87afd996437cf91a",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_Autosave.tox"
   }
  },
  {
   "name": "FNS_BeatMod",
   "title": "BeatMod",
   "kind": "tool",
   "category": "Parameters",
   "description": "Beat-synced modulation on any parameter or ParGroup, locked to the timeline tempo: a wave, a channel of any CHOP, or a gesture you record by hand, gliding in instead of cutting. Tap tempo sets the global BPM, and a manager lists every modulator in the project.",
   "version": "0.1.3",
   "help_url": "https://functionstore.tools/docs/fns-beatmod/",
   "surfaces": [
    "hub"
   ],
   "shortcut": "FNS_BEATMOD",
   "ops": 793,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_HubRegistry"
   ],
   "access": "8323905",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "alt.g",
     "op": "FNS_BeatMod",
     "par": "Shortcutlfo"
    },
    {
     "keys": "alt.r",
     "op": "FNS_BeatMod",
     "par": "Shortcuttap"
    },
    {
     "keys": "alt.shift.g",
     "op": "FNS_BeatMod",
     "par": "Shortcutspeed"
    },
    {
     "keys": "ctrl.alt.g",
     "op": "FNS_BeatMod",
     "par": "Shortcutmenu"
    },
    {
     "keys": "ctrl.alt.r",
     "op": "FNS_BeatMod",
     "par": "Shortcutrecord"
    },
    {
     "keys": "ctrl.shift.g",
     "op": "FNS_BeatMod",
     "par": "Shortcutremove"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_BeatMod.tox",
    "bytes": 502808,
    "sha256": "10f6d988996bf2f665cd613b728c264acc2bd8a50bda26d6726419738596bec1",
    "url": "https://storage.functionstore.tools/fnstools/plus/v3.1.4/FNS_BeatMod.tox"
   }
  },
  {
   "name": "FNS_Collect",
   "title": "Collect",
   "kind": "tool",
   "category": "Workflow",
   "description": "Gather every external file your project references into the project folder and rewrite the parameters to match, so the project travels. Shows the plan before it copies anything.",
   "version": "1.0.4",
   "help_url": "https://functionstore.tools/docs/fns-collect/",
   "surfaces": [],
   "shortcut": "",
   "ops": 32,
   "requires": [],
   "access": "8323905",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "launcher": {
    "surfaces": [
     "context-menu",
     "session"
    ],
    "capabilities": [
     "fns.collect"
    ],
    "seedable": false
   },
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_Collect.tox",
    "bytes": 35710,
    "sha256": "a1a204e34b854b02f0ddf745ec5c03314a1bc9ce6b4ad3f44988533ef37147f3",
    "url": "https://storage.functionstore.tools/fnstools/plus/v3.1.4/FNS_Collect.tox"
   }
  },
  {
   "name": "FNS_CommandKit",
   "title": "CommandKit",
   "kind": "tool",
   "category": "Developer",
   "description": "Drop-in kit that lets ANY component publish quick-launch commands to the TDXL launcher palette: decorate a promoted method, or declare a spec. Guarded: with no launcher in the session nothing happens and nothing errors.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/fns-commandkit/",
   "surfaces": [],
   "shortcut": "",
   "ops": 20,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_CommandKit.tox",
    "bytes": 29646,
    "sha256": "3d5a9050fc6f39dccd44718adc4568e6a117257d741224ed196e121d0d880436",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_CommandKit.tox"
   }
  },
  {
   "name": "FNS_CommandPalette",
   "title": "CommandPalette",
   "kind": "tool",
   "category": "Core",
   "description": "A command palette inside TouchDesigner: every command your FNS tools declare and TouchDesigner's own palette components in one ranked list, opened with a hotkey and aware of what you are looking at. Manage favourites and hidden commands from its tab in Hub.",
   "version": "0.1.3",
   "help_url": "https://functionstore.tools/docs/fns-commandpalette/",
   "surfaces": [
    "hub"
   ],
   "shortcut": "",
   "ops": 215,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_HubRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "ctrl.shift.p",
     "op": "FNS_CommandPalette",
     "par": "Hotkey"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_CommandPalette.tox",
    "bytes": 324134,
    "sha256": "a4c40e6d3eedb89ffb67f687d1e2b0dcc7074765f5a7c56de2d388650ba375c5",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_CommandPalette.tox"
   }
  },
  {
   "name": "FNS_CommandRegistry",
   "title": "CommandRegistry",
   "kind": "tool",
   "category": "Core",
   "description": "Collects the commands your tools declare and serves them to whatever can run them: the launcher palette today, an in-TouchDesigner palette next. Discovery is by tag, so a tool installed before any consumer still appears the moment one arrives.",
   "version": "0.1.4",
   "help_url": "https://functionstore.tools/docs/fns-commandregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 43,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_CommandRegistry.tox",
    "bytes": 87934,
    "sha256": "8a7573de0580007c367790d59f5da35b973fafc5e6fed544322c152955c50dda",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_CommandRegistry.tox"
   }
  },
  {
   "name": "FNS_ConfigHost",
   "title": "ConfigHost",
   "kind": "tool",
   "category": "Developer",
   "description": "A standalone ConfigRegistry host. Drop it into a component to give it roaming settings; its parameters save and reload with your config, with per-parameter and per-page exclusions.",
   "version": "3.0.5",
   "help_url": "https://functionstore.tools/docs/fns-confighost/",
   "surfaces": [],
   "shortcut": "",
   "ops": 28,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_ConfigHost.tox",
    "bytes": 87798,
    "sha256": "b52092bc83851d7264804216958c5dd1024e039ad5f870cf82024013982cecc7",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_ConfigHost.tox"
   }
  },
  {
   "name": "FNS_ConfigRegistry",
   "title": "ConfigRegistry",
   "kind": "core",
   "category": "Core",
   "description": "Settings persistence registry: one aggregated JSON in the user palette, so preferences follow you across projects and survive updates. The raw master, promoted to /sys.",
   "version": "3.0.5",
   "help_url": "https://functionstore.tools/docs/fns-configregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 29,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_ConfigRegistry.tox",
    "bytes": 88230,
    "sha256": "7c1dda7ea643d58e261307af46296c5f1c45b4a2bc2c13519fc170b019fe7e4f",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_ConfigRegistry.tox"
   }
  },
  {
   "name": "FNS_Console",
   "title": "Console",
   "kind": "core",
   "category": "Core",
   "description": "The toolkit's web front, served from inside your project: every tool's settings on one page, the install picker, and any tab a tool contributes. The raw master, promoted to /sys.",
   "version": "3.0.7",
   "help_url": "https://functionstore.tools/docs/fns-console/",
   "surfaces": [],
   "shortcut": "",
   "ops": 28,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_Console.tox",
    "bytes": 97038,
    "sha256": "55ebb4cf84a4a42f21178837c745b68fa5aa9f4d1e9de733f9a2fa44a24476aa",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_Console.tox"
   }
  },
  {
   "name": "FNS_HotkeyManager",
   "title": "HotkeyManager",
   "kind": "tool",
   "category": "Workflow",
   "description": "Unified hotkey discovery, conflict detection and rebinding UI across the whole toolkit.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/fns-hotkeymanager/",
   "surfaces": [
    "hub"
   ],
   "shortcut": "FNS_HOTKEY_MANAGER",
   "ops": 192,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_HubRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "portability": [
    {
     "op": "table_gathered_hotkeys",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/Hotkeys.tsv"
    },
    {
     "op": "table_gathered_hotkeys1",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/Hotkeys.tsv"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_HotkeyManager.tox",
    "bytes": 261790,
    "sha256": "0b743897e35e5137b4dd9154fe5a92cc9fc2db0d2b9624116aa1d9ce780246b9",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_HotkeyManager.tox"
   }
  },
  {
   "name": "FNS_Hub",
   "title": "Hub",
   "kind": "core",
   "category": "Core",
   "description": "The FNS button in TouchDesigner's main-menu bar and the one-stop manager window behind it: the Toolbar, Navbar and Main Menu configurators as tabs, the console, and any tab a tool contributes. Drop a panel COMP on the button to register it into a surface.",
   "version": "3.0.6",
   "help_url": "https://functionstore.tools/docs/fns-hub/",
   "surfaces": [
    "hub",
    "mainmenu"
   ],
   "shortcut": "",
   "ops": 1533,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_Hub.tox",
    "bytes": 1016306,
    "sha256": "543026eb329741a684bbe22018d1deb906308684c58111f8fa92b243be754158",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_Hub.tox"
   }
  },
  {
   "name": "FNS_HubRegistry",
   "title": "HubRegistry",
   "kind": "core",
   "category": "Core",
   "description": "The registry behind Hub's tab bar: tools contribute native panels, viewers or parameter pages as hub tabs. The raw master, promoted to /sys.",
   "version": "3.0.5",
   "help_url": "https://functionstore.tools/docs/fns-hubregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 26,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_HubRegistry.tox",
    "bytes": 75590,
    "sha256": "283e8d5a8dbce696f9cf2e240c9f794d79c442599b4ac8590ec39383bf75070b",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_HubRegistry.tox"
   }
  },
  {
   "name": "FNS_MainMenuRegistry",
   "title": "MainMenuRegistry",
   "kind": "core",
   "category": "Core",
   "description": "TD main-menu surface registry, including project-name display. The raw master, promoted to /sys.",
   "version": "3.0.5",
   "help_url": "https://functionstore.tools/docs/fns-mainmenuregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 27,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [
    "FNS_Hub"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_MainMenuRegistry.tox",
    "bytes": 81758,
    "sha256": "b69f5a132996cdd1a428601965dfcb209ebd0156a466635ec6c59fd79643d72b",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_MainMenuRegistry.tox"
   }
  },
  {
   "name": "FNS_MediaBrowser",
   "title": "MediaBrowser",
   "kind": "tool",
   "category": "Media & Output",
   "description": "See every media file your project uses and which operator uses it, filter to the missing ones, and replace or repoint them in place.",
   "version": "1.0.3",
   "help_url": "https://functionstore.tools/docs/fns-mediabrowser/",
   "surfaces": [],
   "shortcut": "",
   "ops": 38,
   "requires": [],
   "access": "8323905",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "launcher": {
    "surfaces": [
     "context-menu",
     "session"
    ],
    "capabilities": [
     "fns.media-browser"
    ],
    "seedable": false
   },
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_MediaBrowser.tox",
    "bytes": 42134,
    "sha256": "25aa7aa8d97220cc99d46a3c82074ef8f9a975a91de53e7853e72bb6d2799976",
    "url": "https://storage.functionstore.tools/fnstools/plus/v3.1.4/FNS_MediaBrowser.tox"
   }
  },
  {
   "name": "FNS_Navbar",
   "title": "Navbar",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Pane-bar extras: parent-hierarchy navigation, path injection and drag-drop hijack, plus the navbar Configurator.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/fns-navbar/",
   "surfaces": [
    "navbar"
   ],
   "shortcut": "FNS_NAVBAR",
   "ops": 1137,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_NavbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [
    "CustomParTools"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_Navbar.tox",
    "bytes": 548176,
    "sha256": "c83e63577b2b8cb2a31b825a9c89c2641ed194d20675a70a4377f10c30d4b8d9",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_Navbar.tox"
   }
  },
  {
   "name": "FNS_NavbarRegistry",
   "title": "NavbarRegistry",
   "kind": "core",
   "category": "Core",
   "description": "The pane-bar surface registry. The raw master, promoted to /sys; clone it to add your own pane-bar widgets.",
   "version": "3.0.5",
   "help_url": "https://functionstore.tools/docs/fns-navbarregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 27,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [
    "FNS_Hub",
    "FNS_Navbar",
    "FNS_Toolbar"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_NavbarRegistry.tox",
    "bytes": 84590,
    "sha256": "587626886f6ce68c4e15d35894fbf109f2fe3b25fbc0313a20497f80be4d4382",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_NavbarRegistry.tox"
   }
  },
  {
   "name": "FNS_OpMenu",
   "title": "OpMenu",
   "kind": "tool",
   "category": "Surfaces",
   "description": "OP Create dialog extras: the IO filter, operator search words and script injection.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/fns-opmenu/",
   "surfaces": [
    "hub",
    "opmenu"
   ],
   "shortcut": "FNS_OPMOD",
   "ops": 246,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_HubRegistry",
    "FNS_OpMenuRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "portability": [
    {
     "op": "OpSearchWords",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/OpSearchWords.tsv"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_OpMenu.tox",
    "bytes": 328110,
    "sha256": "945f235c4f9630e03bbaefdf16d9e0d2658342ce3dceaadeee484b1a8f49177a",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_OpMenu.tox"
   }
  },
  {
   "name": "FNS_OpMenuRegistry",
   "title": "OpMenuRegistry",
   "kind": "core",
   "category": "Core",
   "description": "OP Create dialog surface registry: search words, row decorations, right-click items, filter stages. The raw master, promoted to /sys.",
   "version": "3.0.5",
   "help_url": "https://functionstore.tools/docs/fns-opmenuregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 28,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_OpMenuRegistry.tox",
    "bytes": 83606,
    "sha256": "9848f98e6b120ea329651bbf47d01c2842fffcc1e0506b3e60ed54e58a5faa46",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_OpMenuRegistry.tox"
   }
  },
  {
   "name": "FNS_PaletteRegistry",
   "title": "PaletteRegistry",
   "kind": "tool",
   "category": "Core",
   "description": "Contribute tabs to TouchDesigner's Palette Browser: a tool publishes a native panel COMP and it appears beside the stock Palette tab, sized to the slot and notified on every tab change.",
   "version": "3.0.5",
   "help_url": "https://functionstore.tools/docs/fns-paletteregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 26,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_PaletteRegistry.tox",
    "bytes": 80198,
    "sha256": "401844c003d20120104bd243920141ca733ac98821d544325797778c454c5faa",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_PaletteRegistry.tox"
   }
  },
  {
   "name": "FNS_PaneTypeRegistry",
   "title": "PaneTypeRegistry",
   "kind": "core",
   "category": "Core",
   "description": "Named, persistent pane-type entries for TD's panebar: any COMP can appear in the pane-type dropdown and be recalled with configurable owner, type, window actions and callbacks.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/fns-panetyperegistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 175,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_PaneTypeRegistry.tox",
    "bytes": 167894,
    "sha256": "cba13cae9cf6ca9034f965b262603b9ba07e556d2b9e0218334de937a9bdbfe9",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_PaneTypeRegistry.tox"
   }
  },
  {
   "name": "FNS_PreviewPanel",
   "title": "PreviewPanel",
   "kind": "tool",
   "category": "Network",
   "description": "A preview pane for whatever you drop on it: TOPs, POPs, SOPs, 3D textures, geometry, panels and other components render in place, and a POP can be opened as a live table or in its own viewer window.",
   "version": "0.1.3",
   "help_url": "https://functionstore.tools/docs/fns-previewpanel/",
   "surfaces": [
    "panebar"
   ],
   "shortcut": "",
   "ops": 3641,
   "requires": [
    "FNS_PaneTypeRegistry"
   ],
   "access": "8323905",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "portability": [
    {
     "op": "UI/POPtoDAT_panel/popViewer/graphs/cam1/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.tog"
    },
    {
     "op": "UI/POPtoDAT_panel/popViewer/docsHelper",
     "par": "externaltox",
     "kind": "tdinstall",
     "path": "<td>/Config/System/sys/docsHelper.tox"
    },
    {
     "op": "UI/POPtoDAT_panel/popViewer/environment/filein1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defenvlight.tog"
    },
    {
     "op": "UI/POPtoDAT_panel/popViewer/cameraViewport/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.geo"
    },
    {
     "op": "UI/POPtoDAT_panel/popViewer/cameraViewportGrid/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.geo"
    },
    {
     "op": "UI/POPtoDAT_panel/popViewer_pop/graphs/cam1/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.tog"
    },
    {
     "op": "UI/POPtoDAT_panel/popViewer_pop/docsHelper",
     "par": "externaltox",
     "kind": "tdinstall",
     "path": "<td>/Config/System/sys/docsHelper.tox"
    },
    {
     "op": "UI/POPtoDAT_panel/popViewer_pop/environment/filein1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defenvlight.tog"
    },
    {
     "op": "UI/POPtoDAT_panel/popViewer_pop/cameraViewport/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.geo"
    },
    {
     "op": "UI/POPtoDAT_panel/popViewer_pop/cameraViewportGrid/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.geo"
    },
    {
     "op": "default_render/light1/cross1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defnull.geo"
    },
    {
     "op": "default_render/T3D_surface/cameraViewport/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.geo"
    },
    {
     "op": "default_render/cameraViewport/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.geo"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_PreviewPanel.tox",
    "bytes": 798658,
    "sha256": "2761faa9b3e2e14abeff2db61dd14561fb55f291b4725b87a41b3c0e5f2e85df",
    "url": "https://storage.functionstore.tools/fnstools/plus/v3.1.4/FNS_PreviewPanel.tox"
   }
  },
  {
   "name": "FNS_Remote",
   "title": "Remote",
   "kind": "tool",
   "category": "Control",
   "description": "Control the project from your phone over your own network: parameter pages, a perform window and multi-touch, paired by QR with no cloud and no account.",
   "version": "1.0.3",
   "help_url": "https://functionstore.tools/docs/fns-remote/",
   "surfaces": [],
   "shortcut": "FNS_REMOTE",
   "ops": 53,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "8323905",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "launcher": {
    "surfaces": [
     "context-menu",
     "session"
    ],
    "capabilities": [
     "fns.mobile-control"
    ],
    "seedable": false
   },
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_Remote.tox",
    "bytes": 128582,
    "sha256": "1d5ae7896abca3890445cce6620913388ba92f3b9466f9fa972de11c701ad5ee",
    "url": "https://storage.functionstore.tools/fnstools/plus/v3.1.4/FNS_Remote.tox"
   }
  },
  {
   "name": "FNS_TimelineRegistry",
   "title": "TimelineRegistry",
   "kind": "tool",
   "category": "Core",
   "description": "Publish a widget into TouchDesigner's timeline bar: transport controls beside the stock ones, an entry on the time-properties block, or a full-width strip in the frame-ruler band that gets its own row.",
   "version": "3.0.5",
   "help_url": "https://functionstore.tools/docs/fns-timelineregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 26,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_TimelineRegistry.tox",
    "bytes": 89158,
    "sha256": "dfef41939d4be98fa27daf6984a858875dee239d78de3b3ef5cd2914e2d6a703",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_TimelineRegistry.tox"
   }
  },
  {
   "name": "FNS_TimelineTools",
   "title": "TimelineTools",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Drive the timeline from your media: pick a movie and an audio file, optionally resize the timeline to fit, and see them behind the ruler and the Keyframer graph as a filmstrip, a waveform and your editor's markers. Key any operators' parameters into an Animation COMP with one press, and play them back from it.",
   "version": "3.0.7",
   "help_url": "https://functionstore.tools/docs/fns-timelinetools/",
   "surfaces": [
    "timeline"
   ],
   "shortcut": "FNS_TIMELINETOOLS",
   "ops": 310,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_TimelineRegistry"
   ],
   "access": "8323905",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "76 keys at frame 8550 (linear, all), 1 channel with no parameter to read",
     "op": "FNS_TimelineTools",
     "par": "Keyframerstatus"
    }
   ],
   "portability": [
    {
     "op": "FNS_Markers/render_chain/cam1/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.tog"
    },
    {
     "op": "FNS_Markers/render_chain/cam_strip/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.tog"
    },
    {
     "op": "FNS_Waveform/render_chain/cam1/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.tog"
    },
    {
     "op": "FNS_Waveform/render_chain/filein1",
     "par": "file",
     "kind": "absolute",
     "path": "<abs>/Aka_Chang_Inst3_V01_3.mp4"
    },
    {
     "op": "FNS_Waveform/render_chain/cam_strip/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.tog"
    },
    {
     "op": "FNS_TimelineBackground/moviefilein",
     "par": "file",
     "kind": "absolute",
     "path": "<abs>/Rick Astley - Never Gonna Give You Up (Official Music Video).mov"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_TimelineTools.tox",
    "bytes": 354542,
    "sha256": "a0324003d5875713d0bdba86ed0bc4ebb2e353a76c84d0ecd7a70f28ca6ee3dc",
    "url": "https://storage.functionstore.tools/fnstools/plus/v3.1.4/FNS_TimelineTools.tox"
   }
  },
  {
   "name": "FNS_Toolbar",
   "title": "Toolbar",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Toolbar extras: the Configurator UI for ordering, grouping and hiding bar widgets, plus stock widgets.",
   "version": "3.0.7",
   "help_url": "https://functionstore.tools/docs/fns-toolbar/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_TOOLBAR",
   "ops": 157,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_Toolbar.tox",
    "bytes": 201878,
    "sha256": "49ee098e0464f3f644e38d4c62e010b5f596b693a512a651e11885bee31799fb",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_Toolbar.tox"
   }
  },
  {
   "name": "FNS_ToolbarRegistry",
   "title": "ToolbarRegistry",
   "kind": "core",
   "category": "Core",
   "description": "The toolbar surface registry and mirror rail. The raw master, promoted to /sys; clone it to put your own tools on the bar.",
   "version": "3.0.5",
   "help_url": "https://functionstore.tools/docs/fns-toolbarregistry/",
   "surfaces": [],
   "shortcut": "",
   "ops": 26,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [
    "FNS_Hub",
    "FNS_Toolbar"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_ToolbarRegistry.tox",
    "bytes": 77310,
    "sha256": "c8cde11317f343d1c8d9e89cb7b4e916e5888e7d51889bb3551444404f22f732",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_ToolbarRegistry.tox"
   }
  },
  {
   "name": "FNS_Updater",
   "title": "Updater",
   "kind": "core",
   "category": "Developer",
   "description": "In-place toolkit updates, with settings preserved across the replacement.",
   "version": "3.0.12",
   "help_url": "https://functionstore.tools/docs/fns-updater/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_UPDATER",
   "ops": 148,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/FNS_Updater.tox",
    "bytes": 250878,
    "sha256": "851906a300bae74e783d751ae402e0bc9025b7b839697fb3be3f7f52ccf7c6ec",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/FNS_Updater.tox"
   }
  },
  {
   "name": "GlobalOutSelect",
   "title": "GlobalOutSelect",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Browse Global OP Shortcuts and the out operators inside them in a tree, and drag any of them into a network as a Select.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/globaloutselect/",
   "surfaces": [
    "hub"
   ],
   "shortcut": "GLOBAL_OUT_SEL",
   "ops": 707,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_HubRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/GlobalOutSelect.tox",
    "bytes": 259958,
    "sha256": "a95f13c83819db24191c58ca38335c97a2b7b641c4ba37a16a4419cad267d6de",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/GlobalOutSelect.tox"
   }
  },
  {
   "name": "GlobalVolControl",
   "title": "GlobalVolControl",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Global audio volume control.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/globalvolcontrol/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_VolControl",
   "ops": 169,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/GlobalVolControl.tox",
    "bytes": 259206,
    "sha256": "1b0228798b7b26fcae1a4a9da0f4ce46f3c6382569d9916bd11995abf876fe80",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/GlobalVolControl.tox"
   }
  },
  {
   "name": "HydroHomie",
   "title": "HydroHomie",
   "kind": "tool",
   "category": "Media & Output",
   "description": "A toolbar reminder to drink water at an interval you set. Off by default.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/hydrohomie/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_HYDROHOMIE",
   "ops": 164,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/HydroHomie.tox",
    "bytes": 202174,
    "sha256": "27faf34e82409aae843ff8c329fdc788f0690b57de28d9f8a4aee161ed1309ed",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/HydroHomie.tox"
   }
  },
  {
   "name": "midiMapper",
   "title": "midiMapper",
   "kind": "tool",
   "category": "Control",
   "description": "Map MIDI controls to parameters, with a learn mode you drive by dropping a parameter on the toolbar button. Mappings are saved into the project folder by design; the tool's own settings roam through config.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/midimapper/",
   "surfaces": [
    "hub",
    "toolbar"
   ],
   "shortcut": "FNS_MULTIMIDI",
   "ops": 365,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_HubRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "author": {
    "name": "AlphaMoonbase.berlin",
    "url": "https://alphamoonbase.de/"
   },
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/midiMapper.tox",
    "bytes": 332518,
    "sha256": "f44eecdb61b902346d51aeda82b145c9d4e6d46f98b2d0b6edc8b908e07af283",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/midiMapper.tox"
   }
  },
  {
   "name": "MISC",
   "title": "MISC",
   "kind": "tool",
   "category": "Workflow",
   "description": "Assorted small utilities that ship together (hog CHOP, mouse input and friends).",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/misc/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_MISC",
   "ops": 140,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/MISC.tox",
    "bytes": 242030,
    "sha256": "a5ab15d27671d793e219d54975389769b553446543628ea53fce6b636af65852",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/MISC.tox"
   }
  },
  {
   "name": "OpenExt",
   "title": "OpenExt",
   "kind": "tool",
   "category": "Developer",
   "description": "Open an operator's extension source quickly.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/openext/",
   "surfaces": [],
   "shortcut": "",
   "ops": 64,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "ctrl.e",
     "op": "OpenExt",
     "par": "Shortcuts"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/OpenExt.tox",
    "bytes": 128358,
    "sha256": "55040587e050ca9484b7253f66ab7b86abb20f7fd3764791cb5ded310b216da0",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/OpenExt.tox"
   }
  },
  {
   "name": "OpTemplates",
   "title": "OpTemplates",
   "kind": "tool",
   "category": "Network",
   "description": "A library of preconfigured operator templates to drop into a network.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/optemplates/",
   "surfaces": [
    "opmenu",
    "toolbar"
   ],
   "shortcut": "FNS_OPTEMPLATES",
   "ops": 527,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_OpMenuRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [
    "AutoRes"
   ],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "portability": [
    {
     "op": "OPTemplates1",
     "par": "externaltox",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/OpTemplates/OPTemplates1.tox"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP/cam1/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.geo"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP/null1/cross1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defnull.geo"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP/light1/cross1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defnull.geo"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP_ortho/cam1/file1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defcam.geo"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP_ortho/null1/cross1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defnull.geo"
    },
    {
     "op": "OPTemplates1/renderTOP/renderTOP_ortho/light1/cross1",
     "par": "file",
     "kind": "tdinstall",
     "path": "<td>/Samples/Geo/defnull.geo"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/OpTemplates.tox",
    "bytes": 368192,
    "sha256": "44abad4a3db1bc6ceb082fb6486b89bacd3d72145457ef71535bf29b60b912d0",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/OpTemplates.tox"
   }
  },
  {
   "name": "OpToClipboard",
   "title": "OpToClipboard",
   "kind": "tool",
   "category": "Network",
   "description": "Copy the selected operator's reference to the system clipboard, ready to paste into an expression.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/optoclipboard/",
   "surfaces": [],
   "shortcut": "",
   "ops": 77,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "shift.ctrl.c",
     "op": "keyboardin1",
     "par": "shortcuts"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/OpToClipboard.tox",
    "bytes": 130502,
    "sha256": "4a455bac8a702d0ec164d68566e8d813404512b6cbb4c9f2f5d777255856e9ec",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/OpToClipboard.tox"
   }
  },
  {
   "name": "oscMapper",
   "title": "oscMapper",
   "kind": "tool",
   "category": "Control",
   "description": "Map OSC messages to parameters. Mappings are saved into the project folder by design.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/oscmapper/",
   "surfaces": [
    "hub"
   ],
   "shortcut": "AMB_OSC_MAPPER",
   "ops": 266,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_HubRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "author": {
    "name": "AlphaMoonbase.berlin",
    "url": "https://alphamoonbase.de/"
   },
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/oscMapper.tox",
    "bytes": 226086,
    "sha256": "3d797500a06ed7f2fe18c37139615ab21f279a39ba65aa648c7f1978d4ac6016",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/oscMapper.tox"
   }
  },
  {
   "name": "OUTPUT",
   "title": "OUTPUT",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Output window and display routing helpers.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/output/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_OUTPUT",
   "ops": 116,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/OUTPUT.tox",
    "bytes": 197494,
    "sha256": "0a095271ce9d2fa922a4817cc8e7b960ec29ef6365a19ea4bf77bf6bbe95ce39",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/OUTPUT.tox"
   }
  },
  {
   "name": "ParOPDrop",
   "title": "ParOPDrop",
   "kind": "tool",
   "category": "Parameters",
   "description": "Create Parameter CHOP/DAT and Parameter Execute DAT nodes inside a COMP from its custom parameters, by drag and drop or hotkey.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/paropdrop/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_POP",
   "ops": 112,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "p",
     "op": "keyboardin1",
     "par": "keys"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/ParOPDrop.tox",
    "bytes": 191958,
    "sha256": "3e02f7eaecda3e0ac7c9fe944e3421b2d35d7449483338459955e365960b37ac",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/ParOPDrop.tox"
   }
  },
  {
   "name": "ParRandomizer",
   "title": "ParRandomizer",
   "kind": "tool",
   "category": "Parameters",
   "description": "Randomize parameter values within range, for quick exploration.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/parrandomizer/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_PARRANDOM",
   "ops": 109,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "alt.r",
     "op": "ParRandomizer",
     "par": "Shortcutpar"
    },
    {
     "keys": "alt.shift.r",
     "op": "ParRandomizer",
     "par": "Shortcutop"
    },
    {
     "keys": "ctrl.alt.shift.r",
     "op": "ParRandomizer",
     "par": "Shortcutresetallcustom"
    },
    {
     "keys": "ctrl.shift.r",
     "op": "ParRandomizer",
     "par": "Shortcutreset"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/ParRandomizer.tox",
    "bytes": 189110,
    "sha256": "5d23e2d12e51262d6234fdec47150ec29a84ed70f59e6ad3f4c130b0b5ae7c9f",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/ParRandomizer.tox"
   }
  },
  {
   "name": "paste_from_clipboard",
   "title": "paste_from_clipboard",
   "kind": "tool",
   "category": "Network",
   "description": "Paste images and data from the system clipboard into TouchDesigner.",
   "version": "3.0.3",
   "help_url": "https://functionstore.tools/docs/paste-from-clipboard/",
   "surfaces": [],
   "shortcut": "",
   "ops": 227,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "alt.v",
     "op": "paste_from_clipboard",
     "par": "Shortcut"
    }
   ],
   "author": {
    "name": "DotSimulate",
    "url": "https://www.patreon.com/dotsimulate"
   },
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/paste_from_clipboard.tox",
    "bytes": 212694,
    "sha256": "6e16454be96d682e68a52c8de2568bfc315df4fad27753a9d9d843a4f9cd32e6",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/paste_from_clipboard.tox"
   }
  },
  {
   "name": "QuickCollapse",
   "title": "QuickCollapse",
   "kind": "tool",
   "category": "Network",
   "description": "Collapse a selection into a component, with an optional customize dialog.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/quickcollapse/",
   "surfaces": [],
   "shortcut": "FNS_QUICKCOLLAPSE",
   "ops": 121,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "ctrl.shift.w",
     "op": "QuickCollapse",
     "par": "Shortcutcustomize"
    },
    {
     "keys": "ctrl.w",
     "op": "QuickCollapse",
     "par": "Shortcut"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/QuickCollapse.tox",
    "bytes": 142622,
    "sha256": "a87d35b1aa690834de5c248b383331a98883d57fb4d5782a2a0121c19429356c",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/QuickCollapse.tox"
   }
  },
  {
   "name": "QuickMarks",
   "title": "QuickMarks",
   "kind": "tool",
   "category": "Network",
   "description": "Bookmark network locations and jump back to them. Bookmarks stay project-local by design.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/quickmarks/",
   "surfaces": [],
   "shortcut": "",
   "ops": 67,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "ctrl.[0-9] ctrl.alt.[0-9] ctrl.alt.shift.[0-9]",
     "op": "keyboardin1",
     "par": "shortcuts"
    }
   ],
   "author": {
    "name": "Alex Guevara",
    "url": "https://alex-guevara.com"
   },
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/QuickMarks.tox",
    "bytes": 132462,
    "sha256": "9a5c6213f94dac8bc1602887e0bf643835ed7df8c5690fa46e4a04213b899d43",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/QuickMarks.tox"
   }
  },
  {
   "name": "QuickPane",
   "title": "QuickPane",
   "kind": "tool",
   "category": "Workflow",
   "description": "Pane layout shortcuts.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/quickpane/",
   "surfaces": [],
   "shortcut": "",
   "ops": 95,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "ctrl.shift.left ctrl.shift.right ctrl.shift.up ctrl.shift.down",
     "op": "keyboardin1",
     "par": "shortcuts"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/QuickPane.tox",
    "bytes": 131582,
    "sha256": "22daea834d7cca2a4fafcfdf3c8ac976e1cd29fcce82aa564bcc5c6675ad765b",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/QuickPane.tox"
   }
  },
  {
   "name": "QuickTime",
   "title": "QuickTime",
   "kind": "tool",
   "category": "Workflow",
   "description": "Timeline and time-related shortcuts.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/quicktime/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_QUICKTIME",
   "ops": 106,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/QuickTime.tox",
    "bytes": 185046,
    "sha256": "b33b1d1834aae3ac07fb05f55ee53558906828bd65359a230384d915a7ee8460",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/QuickTime.tox"
   }
  },
  {
   "name": "ResetPLS1",
   "title": "ResetPLS1",
   "kind": "tool",
   "category": "Workflow",
   "description": "Reset stateful operators (feedback, cache, timers, counts) across the project, with a pattern-based exception list. Bound to ctrl+0.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/resetpls1/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_RPLS",
   "ops": 176,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "cmd.0 ctrl.0",
     "op": "keyboardin_reset",
     "par": "shortcuts"
    }
   ],
   "portability": [
    {
     "op": "table_except_static",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/table_except_static.tsv"
    },
    {
     "op": "table_custom_resetpars",
     "par": "file",
     "kind": "palette",
     "path": "<palette>/FNStools_ext/tables/table_custom_resetpars.tsv"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/ResetPLS1.tox",
    "bytes": 206734,
    "sha256": "7bd56c68d96a140ed10627b105601eab33e35793bd2c46bed9bfa23a6cedb18a",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/ResetPLS1.tox"
   }
  },
  {
   "name": "SetSmoothness",
   "title": "SetSmoothness",
   "kind": "tool",
   "category": "Control",
   "description": "Set Input/Viewer Smoothness on selected TOPs, or on every TOP in the network.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/setsmoothness/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "SMOOTHNESS_SET",
   "ops": 207,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/SetSmoothness.tox",
    "bytes": 242974,
    "sha256": "1c9c49875dac7b4415488ba6b0e82a4f35e739aeeacd11b4192d583658443cc1",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/SetSmoothness.tox"
   }
  },
  {
   "name": "SwapOps",
   "title": "SwapOps",
   "kind": "tool",
   "category": "Network",
   "description": "Swap one operator for another while keeping connections intact.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/swapops/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "SWAP_OPS",
   "ops": 91,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "alt.shift.s",
     "op": "SwapOps",
     "par": "Shortcuts"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/SwapOps.tox",
    "bytes": 186974,
    "sha256": "c96a1089f8a7e220f53b2d1e8c899ebadbe49fbcf65fe81577c112c23b18eb1c",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/SwapOps.tox"
   }
  },
  {
   "name": "SwitchOPs",
   "title": "SwitchOPs",
   "kind": "tool",
   "category": "Network",
   "description": "Switch between operators in place.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/switchops/",
   "surfaces": [],
   "shortcut": "FNS_SWITCHOP",
   "ops": 70,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "ctrl.tab",
     "op": "keyboardin1",
     "par": "shortcuts"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/SwitchOPs.tox",
    "bytes": 128886,
    "sha256": "3b098f91319b0a6998a8ce0a7bf6f1f39b90c22de8a46763832afc36947b735f",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/SwitchOPs.tox"
   }
  },
  {
   "name": "TDX_SearchPalette",
   "title": "TDX_SearchPalette",
   "kind": "tool",
   "category": "Workflow",
   "description": "Search field for TouchDesigner's palette browser, installed into the palette on startup. Vendored TD-SearchPalette by Yea Chen.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/tdx-searchpalette/",
   "surfaces": [],
   "shortcut": "TDX_SEARCH_PALETTE",
   "ops": 107,
   "requires": [
    "FNS_ConfigRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "ctrl.shift.f",
     "op": "TDX_SearchPalette",
     "par": "Shortcuts"
    }
   ],
   "author": {
    "name": "Yea Chen",
    "url": "https://github.com/yeataro/TD-SearchPalette"
   },
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/TDX_SearchPalette.tox",
    "bytes": 102038,
    "sha256": "9586e36160f9d85ef05883635c0b04370ea9859002c459e59638e0c38daf9247",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/TDX_SearchPalette.tox"
   }
  },
  {
   "name": "VSCodeTools",
   "title": "VSCodeTools",
   "kind": "tool",
   "category": "Developer",
   "description": "VS Code integration: open externalized scripts, sync files and generate TouchDesigner type stubs.",
   "version": "3.0.4",
   "help_url": "https://functionstore.tools/docs/vscodetools/",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_VSCODETOOLS",
   "ops": 282,
   "requires": [
    "FNS_ConfigRegistry",
    "FNS_ToolbarRegistry"
   ],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2025.33070",
   "hotkeys": [
    {
     "keys": "ctrl.shift.e ctrl.shift.alt.e",
     "op": "ScriptSyncFile/keyboardin1",
     "par": "shortcuts"
    }
   ],
   "whatsnew": "",
   "artifact": {
    "path": "packaging/dist/VSCodeTools.tox",
    "bytes": 743144,
    "sha256": "c36b641d599ec212cc4eb5f67094508b86d814485e663211ac6b507adc7b20a2",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/VSCodeTools.tox"
   }
  },
  {
   "name": "TDXMap",
   "title": "TDXMap",
   "kind": "tool",
   "foreign": true,
   "category": "Control",
   "description": "MIDI controller mapping with a live web UI: multiple devices, banks, Smart Learn, button actions, 14-bit controls. Pro adds smoothing, pickup mode, easing curves, slot and modify modes.",
   "version": "1.2.0",
   "help_url": "https://tdxmap.functionstore.xyz/docs/",
   "surfaces": [],
   "shortcut": "",
   "ops": 0,
   "requires": [],
   "access": "free",
   "key_available": false,
   "license": "",
   "seats": null,
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true,
   "min_td_build": "2023.12120",
   "hotkeys": [],
   "updates": "self",
   "whatsnew": "",
   "upstream": {
    "manifest": "https://pub-6d70b11fbdda47e1bbbb33f079ca8a7d.r2.dev/manifest.json",
    "url": "https://pub-6d70b11fbdda47e1bbbb33f079ca8a7d.r2.dev/TDXMap.tox",
    "fetched_at": 1788304336
   },
   "placement": "root",
   "author": {
    "name": "Function Store",
    "url": "https://tdxmap.functionstore.xyz"
   },
   "homepage": "https://tdxmap.functionstore.xyz",
   "changelog_url": "https://tdxmap.functionstore.xyz/changelog",
   "artifact": {
    "path": "packaging/dist/TDXMap.tox",
    "bytes": 934742,
    "sha256": "339116402eff423173e944862f7f623c3cede0c1593b6a5ac2328d87a65ac4ba",
    "url": "https://storage.functionstore.tools/fnstools/v3.1.4/TDXMap.tox"
   }
  }
 ]
};
