// GENERATED by packaging/build_manifest.py -- do not edit.
window.FNS_MANIFEST = {
 "schema": 1,
 "toolkit": {
  "name": "FunctionStore_tools_2025",
  "td_build": "099",
  "project": "FunctionStore_tools_2025_DEV.toe"
 },
 "core": [
  "FNS_Config",
  "FNS_HotkeyManager",
  "FNS_MainMenu",
  "FNS_Navbar",
  "FNS_OpMenu",
  "FNS_Toolbar"
 ],
 "categories": [
  "Core",
  "Surfaces",
  "Parameters",
  "Network",
  "Media & Output",
  "Control",
  "Workflow",
  "Developer"
 ],
 "packages": [
  {
   "name": "AltSelect",
   "kind": "tool",
   "category": "Network",
   "description": "Alternative selection helpers for operators in the network editor.",
   "version": "0",
   "build": "23",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "ALT_SELECT",
   "ops": 96,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "AutoCombine",
   "kind": "tool",
   "category": "Network",
   "description": "Combine selected operators into a sensible composite automatically.",
   "version": "0",
   "build": "21",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "AUTO_COMBINE",
   "ops": 123,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "AutoRes",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Project-wide resolution reference that operators can follow instead of hardcoding pixel sizes.",
   "version": "0",
   "build": "26",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "AUTO_RES",
   "ops": 123,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "BorderlessTD",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Borderless TouchDesigner window, plus timeline hiding.",
   "version": "0",
   "build": "49",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_BORDERLESS_TD",
   "ops": 369,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "ColorUI",
   "kind": "tool",
   "category": "Surfaces",
   "description": "Operator and family colour palettes, with the active palette roaming through config.",
   "version": "0",
   "build": "42",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_COLOR_UI",
   "ops": 164,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "CustomParTools",
   "kind": "tool",
   "category": "Parameters",
   "description": "Promote parameters to a parent with binds or expressions, customize name/label/range on drop, plus extension creation, parent shortcuts, parameter clearing and IOP promotion.",
   "version": "0",
   "build": "87",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "navbar",
    "toolbar"
   ],
   "shortcut": "FNS_CPP",
   "ops": 938,
   "requires": [
    "FNS_Config",
    "FNS_Navbar",
    "FNS_Toolbar"
   ],
   "integrates_with": [
    "QuickCollapse"
   ],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "ExprHotStrings",
   "kind": "tool",
   "category": "Parameters",
   "description": "Abbreviations that expand into TouchDesigner expressions as you type in a parameter field.",
   "version": "0",
   "build": "49",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "HOTSTRINGS",
   "ops": 113,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [
    "CustomParTools"
   ],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "ExternalTables",
   "kind": "tool",
   "category": "Developer",
   "description": "Sync table DATs to files on disk for versioning and sharing.",
   "version": "0",
   "build": "22",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "",
   "ops": 87,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "FNS_Config",
   "kind": "core",
   "category": "Core",
   "description": "Settings persistence for every tool: one aggregated JSON in the user palette, so preferences follow you across projects and survive toolkit updates.",
   "version": "0",
   "build": "19",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_CONFIG",
   "ops": 85,
   "requires": [],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "FNS_HotkeyManager",
   "kind": "core",
   "category": "Core",
   "description": "Unified hotkey discovery, conflict detection and rebinding UI across the whole toolkit.",
   "version": "0",
   "build": "35",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_HOTKEY_MANAGER",
   "ops": 198,
   "requires": [],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "FNS_MainMenu",
   "kind": "core",
   "category": "Core",
   "description": "The main-menu surface: registry and Configurator for TD's top bar, including project-name display.",
   "version": "0",
   "build": "",
   "author": "",
   "help_url": "",
   "surfaces": [
    "mainmenu"
   ],
   "shortcut": "FNS_MAINMENU",
   "ops": 371,
   "requires": [],
   "integrates_with": [],
   "tox_carrier": "root",
   "cooking": true
  },
  {
   "name": "FNS_Navbar",
   "kind": "core",
   "category": "Core",
   "description": "The pane-bar surface: registry plus parent-hierarchy navigation, path injection and drag-drop hijack.",
   "version": "0",
   "build": "32",
   "author": "molna@DANI",
   "help_url": "",
   "surfaces": [
    "navbar"
   ],
   "shortcut": "FNS_NAVBAR",
   "ops": 1549,
   "requires": [],
   "integrates_with": [
    "CustomParTools"
   ],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "FNS_OpMenu",
   "kind": "core",
   "category": "Core",
   "description": "The operator-menu surface: contributes search words, row decorations, right-click items and filter stages to TD's OP Create dialog.",
   "version": "0",
   "build": "61",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "opmenu"
   ],
   "shortcut": "FNS_OPMOD",
   "ops": 290,
   "requires": [],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "FNS_Toolbar",
   "kind": "core",
   "category": "Core",
   "description": "The toolbar surface: registry, mirror rail and the Configurator UI for ordering, grouping and hiding bar widgets.",
   "version": "0",
   "build": "32",
   "author": "molna@DANI",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_TOOLBAR",
   "ops": 651,
   "requires": [],
   "integrates_with": [
    "BorderlessTD",
    "midiMapper"
   ],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "GlobalOutSelect",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Pick which operator feeds the global output, from anywhere in the project.",
   "version": "0",
   "build": "30",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "GLOBAL_OUT_SEL",
   "ops": 764,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "GlobalVolControl",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Global audio volume control.",
   "version": "0",
   "build": "22",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_VolControl",
   "ops": 229,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "HydroHomie",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Hydra-style live coding surface inside TouchDesigner.",
   "version": "0",
   "build": "18",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_HYDROHOMIE",
   "ops": 203,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "midiMapper",
   "kind": "tool",
   "category": "Control",
   "description": "Map MIDI controls to parameters. Mappings are saved into the project folder by design.",
   "version": "1",
   "build": "27",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_MULTIMIDI",
   "ops": 299,
   "requires": [],
   "integrates_with": [],
   "tox_carrier": "root",
   "cooking": false
  },
  {
   "name": "MISC",
   "kind": "tool",
   "category": "Workflow",
   "description": "Assorted small utilities that ship together (hog CHOP, mouse input and friends).",
   "version": "0",
   "build": "11",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_MISC",
   "ops": 153,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "MY_HOTKEYS",
   "kind": "tool",
   "category": "Workflow",
   "description": "Convenience hotkeys over stock TouchDesigner actions: open parameters, open the COMP editor, focus the palette search.",
   "version": "0",
   "build": "12",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_HOTKEYS",
   "ops": 94,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "op_store_mod",
   "kind": "tool",
   "category": "Network",
   "description": "Store and recall operator state.",
   "version": "0",
   "build": "10",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_STORE",
   "ops": 144,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "OpenExt",
   "kind": "tool",
   "category": "Developer",
   "description": "Open an operator's extension source quickly.",
   "version": "0",
   "build": "11",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "",
   "ops": 88,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "OpTemplates",
   "kind": "tool",
   "category": "Network",
   "description": "A library of preconfigured operator templates to drop into a network.",
   "version": "0",
   "build": "220",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "opmenu",
    "toolbar"
   ],
   "shortcut": "FNS_OPTEMPLATES",
   "ops": 588,
   "requires": [
    "FNS_Config",
    "FNS_OpMenu",
    "FNS_Toolbar"
   ],
   "integrates_with": [
    "AutoRes"
   ],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "OpToClipboard",
   "kind": "tool",
   "category": "Network",
   "description": "Copy operators to the system clipboard.",
   "version": "0",
   "build": "11",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "",
   "ops": 101,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "oscMapper",
   "kind": "tool",
   "category": "Control",
   "description": "Map OSC messages to parameters. Mappings are saved into the project folder by design.",
   "version": "0",
   "build": "17",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "AMB_OSC_MAPPER",
   "ops": 257,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "OUTPUT",
   "kind": "tool",
   "category": "Media & Output",
   "description": "Output window and display routing helpers.",
   "version": "0",
   "build": "15",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_OUTPUT",
   "ops": 111,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "ParOPDrop",
   "kind": "tool",
   "category": "Parameters",
   "description": "Drop an operator onto a parameter to wire the reference for you.",
   "version": "0",
   "build": "26",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_POP",
   "ops": 154,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "ParRandomizer",
   "kind": "tool",
   "category": "Parameters",
   "description": "Randomize parameter values within range, for quick exploration.",
   "version": "0",
   "build": "35",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_PARRANDOM",
   "ops": 152,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "paste_from_clipboard",
   "kind": "tool",
   "category": "Network",
   "description": "Paste images and data from the system clipboard into TouchDesigner.",
   "version": "0",
   "build": "15",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "",
   "ops": 204,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "root",
   "cooking": true
  },
  {
   "name": "QuickCollapse",
   "kind": "tool",
   "category": "Network",
   "description": "Collapse a selection into a component, with an optional customize dialog.",
   "version": "0",
   "build": "21",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_QUICKCOLLAPSE",
   "ops": 188,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "QuickMarks",
   "kind": "tool",
   "category": "Network",
   "description": "Bookmark network locations and jump back to them. Bookmarks stay project-local by design.",
   "version": "0",
   "build": "10",
   "author": "Dan@DAN-4090",
   "help_url": "https://alex-guevara.com",
   "surfaces": [],
   "shortcut": "",
   "ops": 44,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "root",
   "cooking": true
  },
  {
   "name": "QuickPane",
   "kind": "tool",
   "category": "Workflow",
   "description": "Pane layout shortcuts.",
   "version": "0",
   "build": "23",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "",
   "ops": 119,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "QuickParCustom",
   "kind": "tool",
   "category": "Parameters",
   "description": "Fast custom-parameter editing on the focused operator.",
   "version": "0",
   "build": "10",
   "author": "Dan@DAN-4090",
   "help_url": "https://github.com/function-store/FunctionStore_tools/wiki/03.-Miscellaneous#quickparcustom",
   "surfaces": [],
   "shortcut": "",
   "ops": 138,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [
    "CustomParTools"
   ],
   "tox_carrier": "root",
   "cooking": true
  },
  {
   "name": "QuickTime",
   "kind": "tool",
   "category": "Workflow",
   "description": "Timeline and time-related shortcuts.",
   "version": "0",
   "build": "21",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_QUICKTIME",
   "ops": 148,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "ResetPLS1",
   "kind": "tool",
   "category": "Workflow",
   "description": "Reset stateful operators (feedback, cache, timers, counts) across the project, with a pattern-based exception list. Bound to ctrl+0.",
   "version": "0",
   "build": "34",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_RPLS",
   "ops": 218,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "SetSmoothness",
   "kind": "tool",
   "category": "Control",
   "description": "Set input smoothing/filtering on parameters.",
   "version": "0",
   "build": "14",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "SMOOTHNESS_SET",
   "ops": 250,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "SwapOps",
   "kind": "tool",
   "category": "Network",
   "description": "Swap one operator for another while keeping connections intact.",
   "version": "0",
   "build": "16",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "SWAP_OPS",
   "ops": 134,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "SwitchOPs",
   "kind": "tool",
   "category": "Network",
   "description": "Switch between operators in place.",
   "version": "0",
   "build": "11",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [],
   "shortcut": "FNS_SWITCHOP",
   "ops": 94,
   "requires": [
    "FNS_Config"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "tools_ui",
   "kind": "tool",
   "category": "Surfaces",
   "description": "The tabbed panel that hosts the toolkit's larger tool UIs.",
   "version": "0",
   "build": "31",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "MY_UI",
   "ops": 326,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "UPDATER",
   "kind": "tool",
   "category": "Developer",
   "description": "In-place toolkit updates, with settings preserved across the replacement.",
   "version": "0",
   "build": "26",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_UPDATER",
   "ops": 204,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  },
  {
   "name": "VSCodeTools",
   "kind": "tool",
   "category": "Developer",
   "description": "VS Code integration: open externalized scripts, sync files and generate TouchDesigner type stubs.",
   "version": "0",
   "build": "73",
   "author": "Dan@DAN-4090",
   "help_url": "",
   "surfaces": [
    "toolbar"
   ],
   "shortcut": "FNS_VSCODETOOLS",
   "ops": 389,
   "requires": [
    "FNS_Config",
    "FNS_Toolbar"
   ],
   "integrates_with": [],
   "tox_carrier": "own",
   "cooking": true
  }
 ]
};
