"""Validate docs/ frontmatter and regenerate docs/README.md.

Every file in docs/ carries gray-matter frontmatter -- the same idiom
packaging/docs/ uses and website/tools/build-site.mjs enforces there. This is
the docs/ half: it answers "is this document still true?" mechanically instead
of by reading tone.

    python scripts/docs_index.py            # validate, exit 1 on any problem
    python scripts/docs_index.py --write     # validate, then rewrite docs/README.md

No third-party dependency: the frontmatter subset used here is flat
`key: value`, so it is parsed directly.
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, 'docs')
SKILLS = os.path.join(ROOT, '.claude', 'skills')
INDEX = os.path.join(DOCS, 'README.md')

REQUIRED = ('status', 'summary', 'since')
OPTIONAL = ('verified', 'skill', 'superseded_by')

# status -> (index heading, blurb shown once above the group)
STATUS = {
	'in-force':   ('In force', 'Normative. Conform to these; they describe how the toolkit works today.'),
	'landed':     ('Landed', 'Decision and verification records. Historical, but authoritative on *why*.'),
	'open':       ('Open', 'Planned or approved work that has not been built. Actionable.'),
	'consumed':   ('Consumed', 'Surveys and candidate lists whose work has been done. Kept for the reasoning.'),
	'research':   ('Research', 'Exploration only. Nothing here is a commitment; check `superseded_by`.'),
	'superseded': ('Superseded', 'Kept so the closed path is not re-trodden. Follow `superseded_by`.'),
}

ORDER = ('in-force', 'landed', 'open', 'consumed', 'research', 'superseded')


def parse_frontmatter(text):
	"""Return (dict, body) or (None, text) when the file has no frontmatter."""
	if not text.startswith('---'):
		return None, text
	m = re.match(r'^---\r?\n(.*?)\r?\n---[ \t]*\r?\n', text, re.S)
	if not m:
		return None, text
	meta = {}
	for line in m.group(1).splitlines():
		if not line.strip() or line.lstrip().startswith('#'):
			continue
		if ':' not in line:
			continue
		k, v = line.split(':', 1)
		v = v.strip()
		if len(v) > 1 and v[0] == v[-1] and v[0] in '"\'':
			v = v[1:-1].replace(v[0] * 2, v[0])
		meta[k.strip()] = v
	return meta, text[m.end():]


def collect():
	docs, problems = [], []
	for name in sorted(os.listdir(DOCS)):
		if not name.endswith('.md') or name == 'README.md':
			continue
		path = os.path.join(DOCS, name)
		with io.open(path, encoding='utf-8') as f:
			meta, _ = parse_frontmatter(f.read())
		if meta is None:
			problems.append('%s: no frontmatter' % name)
			continue
		for key in REQUIRED:
			if not meta.get(key):
				problems.append('%s: missing required key %r' % (name, key))
		status = meta.get('status')
		if status and status not in STATUS:
			problems.append('%s: status %r not one of %s'
							% (name, status, ', '.join(ORDER)))
		for key in meta:
			if key not in REQUIRED + OPTIONAL:
				problems.append('%s: unknown key %r' % (name, key))
		target = meta.get('superseded_by')
		if target and not os.path.exists(os.path.join(ROOT, target)):
			problems.append('%s: superseded_by points at missing %s' % (name, target))
		skill = meta.get('skill')
		if skill and not os.path.isdir(os.path.join(SKILLS, skill)):
			problems.append('%s: skill %r has no .claude/skills/%s/' % (name, skill, skill))
		docs.append((name, meta))
	return docs, problems


def render(docs):
	out = [
		'# docs/ — what is in force, what is history',
		'',
		'Generated by `python scripts/docs_index.py --write`. Do not hand-edit:',
		'every row comes from the frontmatter of the file it points at, so fix a',
		'wrong entry in that file and regenerate.',
		'',
		'`status` values: ' + ', '.join('`%s`' % s for s in ORDER) + '.',
		'A `skill` column entry means the *how-to* lives in that skill and this',
		'document keeps the reasoning -- load the skill before acting, read the',
		'document to understand why it is shaped that way.',
		'',
	]
	for status in ORDER:
		group = [(n, m) for n, m in docs if m.get('status') == status]
		if not group:
			continue
		heading, blurb = STATUS[status]
		out += ['## %s' % heading, '', blurb, '',
				'| Document | Summary | Since | Skill |', '|---|---|---|---|']
		for name, meta in group:
			skill = meta.get('skill', '')
			out.append('| [%s](%s) | %s | %s | %s |' % (
				name, name, meta.get('summary', ''), meta.get('since', ''),
				('`/%s`' % skill) if skill else '—'))
		out.append('')
	return '\n'.join(out).rstrip() + '\n'


def main():
	docs, problems = collect()
	if problems:
		print('docs/ frontmatter problems:')
		for p in problems:
			print('  -', p)
		return 1
	print('docs/: %d files, all frontmatter valid' % len(docs))
	if '--write' in sys.argv:
		with io.open(INDEX, 'w', encoding='utf-8', newline='\n') as f:
			f.write(render(docs))
		print('wrote %s' % os.path.relpath(INDEX, ROOT).replace('\\', '/'))
	return 0


if __name__ == '__main__':
	sys.exit(main())
